name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

        # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

        # the go:embed directive will fail the build if this folder does not exist
      - name: Create frontend build folder
        run: |
          mkdir -p web/build
          touch web/build/ignore

      - name: Build
        run: go build cmd/main.go

      - name: Lint
        run: go vet ./...

      - name: Test
        run: go test ./...

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v1.4.4
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: web

      - name: Run ESLint
        run: yarn lint:ci
        working-directory: web

      - name: Run Tests
        run: yarn test
        working-directory: web

      - name: Build
        run: yarn build
        working-directory: web

  golangci-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # the go:embed directive will fail the build if this folder does not exist
      - name: Create frontend build folder
        run: |
          mkdir -p web/build
          touch web/build/ignore

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        timeout-minutes: 5
        with:
          version: v1.39
